<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.4" />

    <!-- Pacotes para manipulação de Docker, arquivos zip e YAML -->
    <PackageReference Include="Docker.DotNet" Version="3.125.15" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />

    <!-- Dapper e DapperExtensions para consultas simples -->
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="DapperExtensions" Version="1.7.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.4" />

    <!-- MySql.Data para fazer a conexão com banco de dados -->
    <PackageReference Include="MySql.Data" Version="9.3.0" />

    <!-- Polly para retry e falhas temporárias -->
    <PackageReference Include="Polly" Version="8.5.2" />
  </ItemGroup>

</Project>
